# Generated by Django 3.2.5 on 2021-07-27 22:09

import candidates.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('candidate_reference', models.CharField(max_length=8, validators=[candidates.validators.validate_8char_length, candidates.validators.validate_alnum])),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_reference', models.CharField(max_length=8, validators=[candidates.validators.validate_8char_length, candidates.validators.validate_alnum])),
                ('score', models.FloatField(validators=[candidates.validators.validate_float_0_100])),
            ],
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(fields=('candidate_reference',), name='unique_candidate'),
        ),
    ]
