# Generated by Django 3.2.5 on 2021-07-27 07:48

import candidates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('candidate_reference', models.CharField(max_length=8, validators=[candidates.models.validate_reference])),
            ],
        ),
    ]
